package by.palto.command;

public enum CommandEnum {

    ADD_NEW_USER,
    GET_ALL_CLIENTS,
    GET_ID_CLIENT_BY_PERS_NUMB,
    DELETE_CLIENT,
    UPDATE_CLIENT,

    GET_ALL_CHARTS_NAMES,
    GET_ID_CHART_BY_NAME,

    GET_ALL_CURRENCY_NAMES,
    GET_CURRENCY_ID_BY_NAME,

    GET_ALL_DEPOSIT_TYPES_NAMES,
    GET_PERCENT_BY_DEPOSIT_TYPE,
    GET_ID_DEPOSIT_TYPE_BY_NAME,

    GET_ALL_CREDIT_TYPES_NAMES,
    GET_PERCENT_BY_CREDIT_TYPE,
    GET_ID_CREDIT_TYPE_BY_NAME,

    ADD_NEW_DEPOSIT_CONTRACT,
    ADD_NEW_CREDIT_CONTRACT,

    END_OF_THE_DAY

}
